esphome:
  name: uth
  friendly_name: UTH
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:
api:
  encryption:
    key: "myKey"
ota:
  platform: esphome
  password: "myPass"
wifi:
  networks:
  - ssid: WiFi-UTH
  manual_ip:
    static_ip: 10.20.0.97
    gateway: 10.20.0.1
    subnet: 255.255.252.0 
    dns1: 10.20.0.1
sensor:
  - platform: adc
    name: "uth-tank"
    pin: GPIO35
    attenuation: 11db
    force_update: true
    filters:
      - median:
            window_size: 60
            send_every: 2
    accuracy_decimals: 3
    update_interval: 1s
  - platform: adc
    name: "uth-pump"
    pin: GPIO34
    attenuation: 11db
    force_update: true
    filters:
      - median:
            window_size: 20
            send_every: 1
    accuracy_decimals: 3
    update_interval: 1s
  - platform: wifi_signal
    name: "uth-wifi"
    update_interval: 60s
  - platform: pulse_counter
    name: "Flow-UTH-Pump"
    pin: GPIO32
    update_interval: 1s
    filters:
    - lambda: return x;
    unit_of_measurement: "pps"  # send data as pulses per second or hz
    accuracy_decimals:  0 
switch:
  - platform: gpio
    name: "UTH-Relay1"
    pin:
      number: 4
      inverted: false
  - platform: gpio
    name: "UTH-Relay2"
    pin:
      number: 16
      inverted: false
  - platform: gpio
    name: "UTH-Relay3"
    pin:
      number: 17
      inverted: false
  - platform: gpio
    name: "UTH-Relay4"
    pin:
      number: 05
      inverted: false
  - platform: gpio
    name: "UTH-Relay5"
    pin:
      number: 19
      inverted: false
  - platform: gpio
    name: "UTH-Relay6"
    pin:
      number: 21
      inverted: false
  - platform: gpio
    name: "UTH-Relay7"
    pin:
      number: 22
      inverted: false
  - platform: gpio
    name: "UTH-Relay8"
    pin:
      number: 23
      inverted: false
